version: '3'
services:
  postgres-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network
  # www:
  #   image: www/nextjs
  #   build: 
  #     context: .
  #     dockerfile: ./apps/www/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres-db
  #   networks:
  #     - app-network
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@postgres-db:5432/postgres?schema=public

networks:
  app-network:
    driver: bridge
